### ISSUE TITLE
Incorrect tray menu positions when taskbar is not on main monitor

### ISSUE THREAD

**Issue by Aqaao** [DvdGiessen/microphone-mute-indicator#10]
This only seems to happen when the taskbar is on the left side of the home screen, I'm guessing it has something to do with the int sign.

![图片](https://github.com/user-attachments/assets/ca0e170c-1826-4646-8299-6ab0ab59472c)

**Comment by DvdGiessen** [comment]
Hm, it's using the coordinates passed with [the `WM_CONTEXTMENU` message](https://learn.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu), but indeed I think how I'm doing the cast does not properly preserve the sign. I'll see if I can reproduce it so I can test a fix.

**Comment by DvdGiessen** [comment]
Straightforward to reproduce by moving the taskbar to a screen to the left of the main screen, and indeed the issue was due to the sign of the coordinate integer not being preserved.

I fixed the bug in 143d9761953f9f7b137a41c8bd6a71c567e278a6 and just now released [v0.3.1](https://github.com/DvdGiessen/microphone-mute-indicator/releases/tag/v0.3.1) which includes the fix.

Thanks for reporting the bug!
