### ISSUE TITLE
Muted Icon

### ISSUE THREAD

**Issue by ByronJim** [DvdGiessen/microphone-mute-indicator#6]
Hi, I like the program
I have a suggestion, can you change the muted icon with another like the mic with a slash.
![image](https://github.com/DvdGiessen/microphone-mute-indicator/assets/41176880/0b8c96d2-7522-4e00-974c-948d7b97ccc3)
Recently I download the program and sometimes I forget what is the muted icon and this is a little confusing.

**Comment by DvdGiessen** [comment]
I didn't design the icons; the program is using the default icons included in Windows. :) That was intentional as it ensures the the icons always match the native Windows style regardless of Windows version and how the user configured their system.

But I'm might be open to contributions adding an option to configure an alternative icon, if it doesn't come with too much code complexity and fits in well with how we can handle custom settings for other of the open feature requests.

**Comment by DvdGiessen** [comment]
A option to configure custom icons has been implemented in [the just released v0.3.0](https://github.com/DvdGiessen/microphone-mute-indicator/releases/tag/v0.3.0). See the README for details on how to use it.
