### ISSUE TITLE
Cannot see indicator when a game is in fullscreen

### ISSUE THREAD

**Issue by ghost** [DvdGiessen/microphone-mute-indicator#8]
Please add a feature where there is an icon above everything, so I can see if I am muted in game.

**Comment by DvdGiessen** [comment]
I think a ingame overlay icon is probably out of scope for this program since that would require a lot more complexity / configuration.

Perhaps a keyboard LED indicator could help your usecase? There's an issue for implementing that (#2), be sure to subscribe to that one if it might be relevant to you. You can also check out the alternative mentioned in that issue, [MicStatus](https://github.com/alandau/MicStatus).
